export const MINTER_OP_CODE_BASE = 0x2000;

export const MINTER_OP_UPDATE_PRICE = MINTER_OP_CODE_BASE + 1;
export const MINTER_OP_UPDATE_PRICE_INC = MINTER_OP_CODE_BASE + 2;
export const MINTER_OP_UPDATE_CONTENT = MINTER_OP_CODE_BASE + 3;

export const MINTER_OP_UPDATE_PROXY_WHITELIST = MINTER_OP_CODE_BASE + 4;
export const MINTER_OP_UPDATE_CODE_AND_DATA = MINTER_OP_CODE_BASE + 5;