export const UTONIC_MANAGER_OP_CODE_BASE = 0x30000;

export const UTONIC_MANAGER_OP_REGISTER = UTONIC_MANAGER_OP_CODE_BASE + 1;
export const UTONIC_MANAGER_OP_INIT = UTONIC_MANAGER_OP_CODE_BASE + 2;
export const UTONIC_MANAGER_OP_SWITCH_OPERATOR_STATUS = UTONIC_MANAGER_OP_CODE_BASE + 3;
