export const PROXY_TON_OP_CODE_BASE = 0x4000;

export const PROXY_TON_OP_UPDATE_RECEIVER = PROXY_TON_OP_CODE_BASE + 1;
export const PROXY_TON_OP_SEND_TON = PROXY_TON_OP_CODE_BASE + 2;
export const PROXY_TON_OP_UPDATE_WITHDRAW_PENDING_TIME = PROXY_TON_OP_CODE_BASE + 3;
export const PROXY_TON_OP_WITHDRAW_NOTIFICATION = PROXY_TON_OP_CODE_BASE + 3;