export const USER_STRATEGY_INFO_STATUS_NO_DELEGATE = 0;
export const USER_STRATEGY_INFO_STATUS_DELEGATE_DONE = 1;
export const USER_STRATEGY_INFO_STATUS_PENDING_UPDATE_UNDELEGATE = 2;
export const USER_STRATEGY_INFO_STATUS_PENDING_UPDATE_DELEGATE = 3;