export const STRATEGY_OP_CODE_BASE = 0x20000;

export const STRATEGY_OP_INIT_USER_INFO = STRATEGY_OP_CODE_BASE + 1;

export const STRATEGY_OP_ADMIN_UPDATE_OPERATOR_SHARE = STRATEGY_OP_CODE_BASE + 2;
export const STRATEGY_OP_ADMIN_DELEGATE_ACK = STRATEGY_OP_CODE_BASE + 3;
export const STRATEGY_OP_ADMIN_UNDELEGATE_ACK = STRATEGY_OP_CODE_BASE + 4;
export const STRATEGY_OP_ADMIN_CANCEL_USER_PENDING = STRATEGY_OP_CODE_BASE + 5;
export const STRATEGY_OP_ADMIN_UPDATE_WITHDRAW_PENDING_TIME = STRATEGY_OP_CODE_BASE + 6;
export const STRATEGY_OP_ADMIN_UPDATE_UTONIC_MANAGER = STRATEGY_OP_CODE_BASE + 7;
export const STRATEGY_OP_ADMIN_UPDATE_TOKEN_RECEIVER = STRATEGY_OP_CODE_BASE + 8;
export const STRATEGY_OP_ADMIN_EXTRACT_TOKEN = STRATEGY_OP_CODE_BASE + 9;
export const STRATEGY_OP_ADMIN_UPDATE_CAPACITY = STRATEGY_OP_CODE_BASE + 10;