export const PROXYLST_CODE_BASE = 0x5000;

export const PROXYLST_UPDATE_ADMIN = PROXYLST_CODE_BASE + 1;
export const PROXYLST_UPDATE_PRICE = PROXYLST_CODE_BASE + 2;
export const PROXYLST_UPDATE_PROXYLST_WALLET = PROXYLST_CODE_BASE + 3;
export const PROXYLST_UPDATE_LST_TON_RECEIVER = PROXYLST_CODE_BASE + 4;
export const PROXYLST_SEND_LST_TON = PROXYLST_CODE_BASE + 5;