export const STAKE_OP_CODE_BASE = 0x10000;

export const STAKE_OP_INIT = STAKE_OP_CODE_BASE + 1;
export const STAKE_OP_DELEGATE = STAKE_OP_CODE_BASE + 2;
export const STAKE_OP_DELEGATE_ACK = STAKE_OP_CODE_BASE + 3;

export const STAKE_OP_UNDELEGATE = STAKE_OP_CODE_BASE + 4;
export const STAKE_OP_UNDELEGATE_ACK = STAKE_OP_CODE_BASE + 5;
export const STAKE_OP_BURN = STAKE_OP_CODE_BASE + 6;
export const STAKE_OP_WITHDRAW = STAKE_OP_CODE_BASE + 7;
export const STAKE_OP_DEPOSIT = STAKE_OP_CODE_BASE + 8;
export const STAKE_OP_DEPOSIT_ACK = STAKE_OP_CODE_BASE + 9;
export const STAKE_OP_CANCEL_PENDING = STAKE_OP_CODE_BASE + 10;

export const STAKE_OP_ADD_OPT_SHARE = STAKE_OP_CODE_BASE + 11;
export const STAKE_OP_DEC_OPT_SHARE = STAKE_OP_CODE_BASE + 12;
export const STAKE_OP_UPDATE_OPT_SHARE_ACK = STAKE_OP_CODE_BASE + 13;

export const STAKE_OP_QUERY = STAKE_OP_CODE_BASE + 14;
export const STAKE_OP_QUERY_ACK = STAKE_OP_CODE_BASE + 15;

export const STAKE_OP_ADMIN_UPDATE_ADMIN = STAKE_OP_CODE_BASE + 16;
export const STAKE_OP_ADMIN_ACCEPT_ADMIN = STAKE_OP_CODE_BASE + 17;
export const STAKE_OP_ADMIN_UPDATE_CODE = STAKE_OP_CODE_BASE + 18;
