export const STAKE_ERR_CODE_BASE = 0x100;

export const STAKE_ERR_INVALID_AMOUNT = STAKE_ERR_CODE_BASE + 1;

export const STAKE_ERR_WRONG_CALLER = STAKE_ERR_CODE_BASE + 4;
export const STAKE_ERR_INSUFFICIENT_BALANCE = STAKE_ERR_CODE_BASE + 5;
export const STAKE_ERR_UNAUTHORIZED = STAKE_ERR_CODE_BASE + 6;
export const STAKE_ERR_NOT_ENABLED = STAKE_ERR_CODE_BASE + 7;
export const STAKE_ERR_INSUFFICIENT_VALUE = STAKE_ERR_CODE_BASE + 8;
export const STAKE_ERR_INVALID_RECIPIENT_ADDRESS = STAKE_ERR_CODE_BASE + 9;
export const STAKE_ERR_INVALID_WITHDRAW_AMOUNT = STAKE_ERR_CODE_BASE + 10;
export const STAKE_ERR_INSUFFICIENT_WITHDRAW_CAPACITY = STAKE_ERR_CODE_BASE + 11;
export const STAKE_ERR_TON_RECEIVER_NOT_SET = STAKE_ERR_CODE_BASE + 12;
export const STAKE_ERR_UTON_RECEIVER_NOT_SET = STAKE_ERR_CODE_BASE + 13;
export const STAKE_ERR_BOUNCE_INVALID_OP = STAKE_ERR_CODE_BASE + 14;


export const STAKE_ERR_INVALID_STATUS = STAKE_ERR_CODE_BASE + 15;
export const STAKE_ERR_INSUFFICIENT_SHARES = STAKE_ERR_CODE_BASE + 16;