
export const COMMON_OP_CODE_BASE = 0x1000;
export const COMMON_OP_STAKE = COMMON_OP_CODE_BASE + 3;
export const COMMON_OP_BURN_NOTIFICATION = COMMON_OP_CODE_BASE + 4;


export const COMMON_OP_UPDATE_ADMIN = COMMON_OP_CODE_BASE + 3;
export const COMMON_OP_ACCEPT_ADMIN = COMMON_OP_CODE_BASE + 4;